apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: drupal
  name: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: drupal
    spec:
      volumes:
       - name: mypd
         persistentVolumeClaim:
           claimName: drupal-pvc
      initContainers:
      - name: init-sites-volume
        image: drupal:8.6
        volumeMounts:
         - name: mypd
           mountPath: "/data"
        command: [ "/bin/bash", "-c" ]
        args: [ 'cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R' ]
      containers:
      - image: drupal:8.6
        name: drupal
        volumeMounts:
         - name: mypd
           mountPath: /var/www/html/modules
           subPath: modules
         - name: mypd
           mountPath: /var/www/html/profiles
           subPath: profiles
         - name: mypd
           mountPath: /var/www/html/sites
           subPath: sites
         - name: mypd
           mountPath: /var/www/html/themes
           subPath: themes
           
        resources: {}
status: {}
