apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-pod-cm
  name: nginx-pod-cm
spec:
  containers:
  - image: nginx
    name: nginx-pod-cm
    envFrom:
     - configMapRef:
         name: db-config
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
