apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-cm-prop
  name: nginx-cm-prop
spec:
  containers:
  - image: nginx
    name: nginx-cm-prop
    envFrom:
     - configMapRef:
         name: test-config
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
